const CACHE="game-time-bank-v32";
const ASSETS=[
  "./",
  "./index.html",
  "./style.css",
  "./app.js",
  "./manifest.webmanifest",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./image/Cleared_2.webp",
  "./image/Cleared_4.webp",
  "./image/Cleared_6.webp",
  "./image/Cleared_all.webp",
  "./image/-.webp",
  "./image/+.webp",
  "./sound/se/clear.opus",
  "./sound/se/perfect.opus",
  "./sound/se/pi_memu.opus",
  "./sound/se/pikon_15hun.opus",
  "./sound/voice/finish.opus",
  "./sound/voice/nokori1hun.opus",
  "./sound/voice/nokori5hun.opus",
  "./sound/voice/nokori10hun.opus",
  "./sound/voice/nokori30hun.opus",
  "./sound/voice/30min_passed.opus",
  "./sound/voice/60min_passed.opus",
  "./sound/voice/start.opus",
  "./sound/voice/stop.opus"
];
self.addEventListener("install",e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS)).then(()=>self.skipWaiting())));
self.addEventListener("activate",e=>e.waitUntil(self.clients.claim()));
self.addEventListener("fetch",e=>e.respondWith(caches.match(e.request).then(r=>r||fetch(e.request))));
